### ISSUE TITLE
Could i use this code for a Blender Addon

### ISSUE THREAD

**Issue by schroef** [rensbaardman/ASE-to-CSS#1]
Hi Rens,

i was looking into some python to find existing code which can read ASE files. I found some readers for Gimp which use python, but looked to complicated to strip it. After a while i found you code and at first it wasnt working ofcourse cause of the missing swatch_parser. After merging the swatch parser into a single file and together with you code i get Blender to generate the CSS file.

However i would to make a addon which will make sort of a palette for Blender.

Is that okay with you? I'll keep most of you code as it, as it simple works and also will add link to your original code ofcourse

**Comment by schroef** [comment]
After printing the data from the parser, i think that already is what i need :)

**Comment by rensbaardman** [comment]
Hi, thanks for your interest 😀 I added the MIT License, so you should be able to do with whatever and however you like!

But, this was just a one-off project that I quickly hacked together. I might clean it up and add some tests later on. Until that time: use it at your own risk 😉

I'm not sure how Blender works, but if you just need to parse ASE files, it's better to use the [`swatch`](https://github.com/nsfmc/swatch) parser directly. It is available from PyPI (`pip install swatch`).
