### ISSUE TITLE
ModuleNotFoundError: No module named 'swatch'

### ISSUE THREAD

**Issue by nclm** [rensbaardman/ASE-to-CSS#3]
Hello, thanks for making this!

I get this error while running it:

```
nicolas@xxx colors % python3 ase-to-css.py xxx.ase 
Traceback (most recent call last):
  File "xxx/colors/ase-to-css.py", line 1, in <module>
    import swatch as swatch_parser
ModuleNotFoundError: No module named 'swatch'
```

This is on macOS 14.0.

Any idea of what is happening?

**Comment by rensbaardman** [comment]
Hi @nclm, parsing the `.ase`-file is done by the library [swatch](https://github.com/nsfmc/swatch). To install:

```
$ pip install swatch
```

As a disclaimer, I haven't looked at this project in years, and I can't guarantee the quality. I wouldn't use it in production.

**Comment by nclm** [comment]
Thanks. Somehow that command doesn’t parse on my system, but I will look into it.

Thanks no worries, I wouldn’t use without double checking all the colours are there and correct, I was just looking for a quick way to transfer my entire colour palette into CSS! Ended up doing it by hand for that project :)

**Comment by rensbaardman** [comment]
Make sure to not copy the `$`-sign, it signifies the start of a line in the terminal.

**Comment by nclm** [comment]
Thanks this I knew, but I get this error:

```
zsh: /usr/local/bin/pip: bad interpreter: /usr/bin/python: no such file or directory
```

I guess there is just something off on my python installation, as I never use it. 

No worries though, I don’t need it anytime soon :)

**Comment by nclm** [comment]
Fixed by just typing `pip3` instead of `pip` :)

And ASE-to-CSS works, thanks!
